//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankomatSimulazione
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bankomat2Entities : DbContext
    {
        public Bankomat2Entities()
            : base("name=Bankomat2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banche> Banche { get; set; }
        public virtual DbSet<Banche_Funzionalita> Banche_Funzionalita { get; set; }
        public virtual DbSet<ContiCorrente> ContiCorrente { get; set; }
        public virtual DbSet<Funzionalita> Funzionalita { get; set; }
        public virtual DbSet<Movimenti> Movimenti { get; set; }
        public virtual DbSet<Utente> Utenti { get; set; }
    }
}
