//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entityframework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities1 : DbContext
    {
        public masterEntities1()
            : base("name=masterEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<orderitems> orderitems { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<utenti> utenti { get; set; }
    }
}
